product_app/__init__.py
from flask import Flask, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, current_user

from functools import wraps # Para maneho de decoradores para sesiones

app=Flask(__name__)

app.config.from_object('configuration.DevelopmentConfig')
db=SQLAlchemy(app)

login_manager=LoginManager()
login_manager.init_app(app)
login_manager.login_view='fauth.login'

from product_app.module_auth.views_auth import logout

def rol_admin_need(f):
    @wraps(f)
    def wrapper(*args, **kwds):
        if current_user.rol.value != 'admin':
            logout()
            return redirect(url_for('fauth.login'))
            #login_manager.unauthorized()
            #return 'Tu debes ser un admin',403
            #print('Calling decorated function ' + str(current_user.rol.value))
        return f(*args, **kwds)
    return wrapper

#registrar rest api
from product_app.rest_api.category_api import category_view
from product_app.rest_api.product_api import product_view

#importar las vistas
from product_app.module_product.views_product import product
from product_app.module_category.views_category import category
#from product_app.module_auth.views_auth import auth
from product_app.module_auth.fauth.views_auth import fauth

app.register_blueprint(product)
app.register_blueprint(category)
#app.register_blueprint(auth)
app.register_blueprint(fauth)

with app.app_context():
    db.create_all()
   
 
def reverse_filter(s):
     return s[::-1]

def mydouble_filter(n:int):
    return n*2

app.jinja_env.filters['mydouble'] = mydouble_filter
app.jinja_env.filters['reverse_filter'] = reverse_filter

product_app/module_product/views.py
from flask import Blueprint, render_template, abort, request, redirect, url_for, flash, get_flashed_messages
from product_app.module_product.model.products import PRODUCTS
from product_app.module_product.model.product import Product
from product_app import db
from product_app.module_product.model.product import ProductForm


product=Blueprint('product', __name__)

@product.route('/test')
def test():
    products=Product.query.paginate(page=1,per_page=5).items
    print(products)
    return render_template('product/index.html')
    
@product.route('/product')
@product.route('/product/<int:page>')
def index(page=1):
    return render_template('product/index.html', products=Product.query.paginate(page=page,per_page=5))

@product.route('/product/<int:id>')
def show(id):
    #product=PRODUCTS.get(id)
    product=Product.query.get_or_404(id)
    print(type(product))
    #if not product:
    #    abort(404)
    return render_template('product/show.html', product=product)

@product.route('/product-delete/<int:id>')
def delete(id):
    product=Product.query.get_or_404(id)
    db.session.delete(product)
    db.session.commit()
    flash('Producto eliminado con exito')
    return redirect(url_for('product.index'))

@product.route('/product-create', methods=('GET','POST'))
def create():
    #print(get_flashed_messages())
    form=ProductForm(meta={'csrf':False})
    if form.validate_on_submit():
        p=Product(request.form.get('name'), request.form.get('price'))
        db.session.add(p)
        db.session.commit()
        flash('Producto ingresado con exito')
        return redirect(url_for('product.create'))
    if form.errors:
        flash(form.errors, 'danger')
    return render_template('product/create.html', form=form)

@product.route('/product-update/<int:id>', methods=['GET','POST'])
def update(id):
    product=Product.query.get_or_404(id)
    form=ProductForm(meta={'csrf':False})
    
    if request.method == 'GET':
        form.name.data=product.name
        form.price.data=product.price
    
    if form.validate_on_submit():
        #Actualizar el producto
        product.name=form.name.data
        product.price=form.price.data
        
        db.session.add(product)
        db.session.commit()
        flash('Producto actualizado con exito')
        return redirect(url_for('product.update', id=product.id))
    if form.errors:
        flash(form.errors, 'danger')
    return render_template('product/update.html', product=product, form=form)

@product.route('/filter/<int:id>')
def filter(id):
    product=PRODUCTS.get(id)
    return render_template('product/filter.html', product=product)

@product.app_template_filter('igv')
def igv_filter(product):
    if product['price']:
        return product['price'] * 1.18
    return 'Sin precio'

product_app/templates/category/_form.html
<div class="form-group">
    {{ form.name.label }} 
    {{ form.name(class='form-control') }}
</div>

product_app/templates/category/create.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('category.create') }}" method="POST">
        {% include 'category/_form.html' %}
        <input type="submit" class="btn btn-primary btn-lg btn-block" value="Enviar">
    </form>
{% endblock %}

product_app/templates/category/index.html
{% extends 'layout/base.html' %}
{% from 'macro/_pagination.html' import m_pagination %}

{% block container %}

  <a href="{{ url_for('category.create') }}" class="btn btn-primary mt-2 mb-2"><i class="fa fa-plus"></i> Crear</a>
    <br>
    <div class="list-category">
    {% for category in categories.items %}
        <div class="card mt-2 {{ loop.cycle('odd','even') }}">
          <div class="card-body pb-2 pt-3">
            <h3>
              <a href="{{ url_for('category.show', id=category['id']) }}">{{ category['name'] }}</a>
            </h3>  
              <a class="btn btn-success btn-sm" href="{{ url_for('category.update', id=category['id']) }}"><i class="fa fa-edit"></i> Editar</a>
              <button data-toggle="modal" data-target="#deleteModal" class="btn btn-danger btn-sm" data-name="{{category['name']}}" data-id="{{category['id']}}" href="{{ url_for('category.delete', id=category['id']) }}"><i class="fa fa-trash"></i> Eliminar</Button>    
          </div> 
        </div>       
    {% endfor %}
  </div>
    <br>
      <div class=page-items>
        {{ categories.first }} - {{ categories.last }} of {{ categories.total }}
      </div>

      {{ m_pagination(categories) }}

      <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Borrar: <span></span></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Seguro que desea borrar el registro seleccionado?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
              <a href="#" id="deleteProduct" class="btn btn-danger">Borrar</a>
            </div>
          </div>
        </div>
      </div>

      <script>
        window.onload=function(){
          $('#deleteModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var name = button.data('name') 
            var id = button.data('id')
            var modal = $(this)
            modal.find('.modal-title span').text(name)
            $('#deleteProduct').attr('href', '/category-delete/'+id)
          })
        }
      </script>
    

{% endblock %}

product_app/templates/category/show.html
{% extends 'layout/base.html' %}

{% block container %}
    <h3>{{product['name']}}</h3>
    <p>{{product['category']}}</p>
    <p>Precio: {{ product['price'] }}</p>

    {% if product['price'] >= 1000 %}
        <p>Precio regular</p>
    {% else %}
        <p>Precio oferta!</p>
    {% endif %}
{% endblock %}

product_app/templates/category/update.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('category.update', id=category.id) }}" method="POST">
        {% include 'category/_form.html' %}
        <input type="submit" class="btn btn-primary btn-lg btn-block" value="Actualizar">
    </form>
{% endblock %}

product_app/templates/fragment/_alert.html
    {% with messages = get_flashed_messages() %}
    {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success fade show mt-2">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
    {% endif %}
    {% endwith %}

product_app/templates/fragment/_footer.html
<footer class="bg-light text-center text-lg-start bg-primary">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0,0,255,1.0);">
      © 2020 Copyright:
      <a class="text-dark" href="https://piratasunidos.com/">PiratasUnidos.com</a>
    </div>
    <!-- Copyright -->
  </footer>

product_app/templates/fragment/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">FLASK</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if current_user.username %}
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('product.index') }}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
              CRUD
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{{ url_for('product.index') }}">Productos</a>
              <a class="dropdown-item" href="{{ url_for('category.index') }}">Categorias</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>         
        {% endif %}

      </ul>

      <ul class="navbar-nav">

        {% if current_user.username %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
             Hola: {{ current_user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="#">Perfil</a>
              <a class="dropdown-item" href="{{ url_for('fauth.logout') }}">Logout</a>
            </div>
          </li>
        {% else %}      
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('fauth.login') }}">Login</a>
          </li>
        {% endif %}

      </ul>
    </div>
  </nav>

product_app/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/product/style.custom.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fontawsome/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='global/css/style.custom.css') }}">
    <title>CRUD</title>
</head>
<body>
    <header>
        {% include 'fragment/_nav.html' %}
    </header>
    
    <div class="container">
        {% include 'fragment/_alert.html' %}
        {% block container %}{% endblock %}
    </div>
    
    <footer> {% include 'fragment/_footer.html' %}</footer>
    <script src="{{ url_for('static', filename='bootstrap/js/jquery.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/popper.min.js') }}"></script>
</body>
</html>

product_app/templates/macro/_pagination.html
{% macro m_pagination(pagination) %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if pagination.has_prev %}
                <li class="page-item"></li><a class="page-link" href="{{ url_for('product.index', page=pagination.prev_num) }}">&laquo;</a></li>
            {% endif %}

            {% for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                    <li class="page-item"></li><a class="page-link" href="{{ url_for('product.index', page=page) }}">{{ page }}</a></li>
                {% else %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">{{ page }}</a>
                    </li>
                {% endif %}
            {% else %}
                <span class=ellipsis>…</span>
            {% endif %}
            {% endfor %}

            {% if pagination.has_next %}
                <li class="page-item"></li><a class="page-link" href="{{ url_for('product.index', page=pagination.next_num) }}">&raquo;</a></li>
            {% endif %}

        </ul>
    </nav>   
{%- endmacro %}

product_app/templates/product/_form.html
<div class="form-group">
    {{ form.name.label }} 
    {{ form.name(class='form-control') }}
</div>

<div class="form-group">
    {{ form.price.label }} 
    {{ form.price(class='form-control') }}
</div>

<div class="form-group">
    {{ form.category_id.label }} 
    {{ form.category_id(class='form-control') }}
</div>

product_app/templates/product/create.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('product.create') }}" method="POST">
        {% include 'product/_form.html' %}
        <input type="submit" value="Enviar">
    </form>
{% endblock %}

product_app/templates/product/filter.html
<h3>{{product['name']}}</h3>
<p>{{product['category']}}</p>
<p>Filtro default: {{ product['price'] | default('Sin precio', True) }}</p>

 {{ "<h1>Filtro safe: Hola mundo</h1>" | safe }}
Filtro truncate: {{ "Este es un texto demasiado largo" | truncate(7) }}
Filtro count: {{ "Este es un texto demasiado largo" | count }}
<p>Filtro float: {{ "70.67" | float }}</p>
<p>Filtro int: {{ "70.67" | int }}</p>
<p>Filtro de redondeo: {{ 3.14159248843 | round(3) }}</p>
<p>Filtro de array a texto: {{ ['iPhone','iPad'] | join(',') }}</p>
<p>Filtro de contar elementos: {{ ['iPhone','iPad'] | length() }}</p>
<p>Filtro de convertir a json: {{ {'status':True, 'price':45, 'existence':'Yes'}  | tojson }}</p>
<p>Filtro reverso: {{ "Este es un texto" | reverse }}</p>
<p>Filtro global custom: {{ 30 | mydouble }}</p>
{{ 50 | mydouble }}

product_app/templates/product/index.html
{% extends 'layout/base.html' %}

{% block container %}
    {% for product in products.items if product['price'] %}
        <div>
            <a href="{{ url_for('product.show', id=product['id']) }}">{{ product['name'] }}</a>
            <a href="{{ url_for('product.update', id=product['id']) }}">Editar</a>
            <a href="{{ url_for('product.delete', id=product['id']) }}">Eliminar</a>
            {{ loop.index0 }}
        </div>     
    {% endfor %}

    <div class=page-items>
        {{ products.first }} - {{ products.last }} of {{ products.total }}
      </div>
      <div class=pagination>
        {% for page in products.iter_pages() %}
          {% if page %}
            {% if page != products.page %}
              <a href="{{ url_for('product.index', page=page) }}">{{ page }}</a>
            {% else %}
              <strong>{{ page }}</strong>
            {% endif %}
          {% else %}
            <span class=ellipsis>…</span>
          {% endif %}
        {% endfor %}
      </div>
      
{% endblock %}

product_app/templates/product/update.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('product.update', id=product.id) }}" method="POST">
        {% include 'product/_form.html' %}
        <input type="submit" value="Actualizar">
    </form>
{% endblock %}